openapi: 3.0.1
info:
  title: '@jupiterone/graph-qualys'
  description: Qualys integration for JupiterOne
  x-cortex-git:
    github:
      repository: JupiterOne/graph-qualys
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-service-groups: tier-4
  x-cortex-tag: '@jupiterone/graph-qualys'
